title: Spektrum Autyzmu
description: Selekcjonowana lista polskojęzycznych zasobów przeznaczonych dla osób w Spektrum Autyzmu.

lang: pl-PL

remote_theme: mattesilver/slate
show_downloads: false

favicon: assets/images/as.png
favicon_mime: image/png
