baseURL: https://spektrum-autyzmu.github.io/
defaultContentLanguage: pl

languageCode: pl-PL

module:
  hugoVersions:
    min: 0.56.0
  imports:
  - path: github.com/mattesilver/hugo-goat-counter

taxonomies:
disableKinds:
- sitemap
- RSS

title: Spektrum Autyzmu

params:
  description: Strona startowa
  title: Spektrum Autyzmu
  favicon:
    mime: image/png
    src: images/as.png
  goatCounterId: 7b76bb
